server:
  port: 10001

spring:
  datasource:                                           # 数据源的相关配置
    # 拆分数据源到独立的数据库实例或者schema
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 1990425lc

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl