############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  #  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  application:
    name: foodie-search-service
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-nodes: 43.154.87.31:9300  # PS:后端对接的接口号为9300, es为9200
      cluster-name: es6

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

# 关闭actuator对es的检查，否则报错
management:
  health:
    elasticsearch:
      enabled: false

